name: Samit Chaudhuri
github: [metadata]
safe: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-mentions	
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed 
